name: Publish package to NPM

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: 'Bump version'
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'
          - 'premajor'
          - 'preminor'
          - 'prepatch'
          - 'prerelease'

jobs:
  publish:
    if: github.actor == 'leanderpaul' && github.triggering_actor == 'leanderpaul' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git user config
        run: |
          git checkout -b release
          git push --set-upstream origin release
          git config user.name "Leander Paul"
          git config user.email "leanderpaul97@outlook.com"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Bump version
        run: pnpm lerna publish ${{ github.event.inputs.bump }} -y
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: PR to main
        run: |
          gh pr create -f
          gh pr merge --auto -s
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
