name: Publish package to NPM

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: 'Bump version'
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'
          - 'premajor'
          - 'preminor'
          - 'prepatch'
          - 'prerelease'

jobs:
  publish:
    if: github.actor == 'leanderpaul' && github.triggering_actor == 'leanderpaul' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Release branch
        run: |
          git checkout -b release
          git push --set-upstream origin release

      - name: Set Git user config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Bump version
        run: bun lerna publish ${{ github.event.inputs.bump }} -y
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: PR to main
        run: |
          gh pr create -f
          gh pr merge --auto -s
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
